package yowfree

import scalaz._
import Scalaz._
import scalaz.{Free => _}

/** 
 * The Free monad generated by some functor F.
 */
trait Free[F[_], +A] {

  def flatMap[B](f: A => Free[F, B])
                (implicit F: Functor[F]): Free[F, B]

}




case class Return[F[_], +A](a: A) extends Free[F, A] {
  
  /**
   * Exercise 1a.
   * Implement flatMap for Return. 
   */
  override def flatMap[B](f: A => Free[F, B])
                         (implicit F: Functor[F]): Free[F, B] = f(a)
}



case class Suspend[F[_], A](functor: F[Free[F, A]]) extends Free[F, A] {
  /**
   * Exercise 1b.
   * Implement flatMap for Suspend. 
   */
  override def flatMap[B](f: A => Free[F, B])
                         (implicit F: Functor[F]): Free[F, B] = Suspend(functor map (_ flatMap f))
}

object Free {

  /**
   * Exercise 1c.
   * 
   * Implement liftF, lifting a functor into its free monad.
   */
  def liftF[F[_]: Functor, A](fa: => F[A]): Free[F, A] = ???

}





